name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GO_VERSION: 1.15
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod tidy

    #   - name: Run tests
    #     run: go test ./...

      - name: Build
        run: go build -o mock-server ./cmd/mock-server

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        run: golangci-lint run ./...

